---
# file: roles/postgresql/tasks/monit.yml
- name: add postgresql to monitoring
  template:
    src: postgresql.j2
    dest: /etc/monit/conf.d/postgresql
    mode: 0600
    owner: root
    group: root
  notify:
    - reload monit
