---
# file: roles/nginx/tasks/monit.yml
- name: add nginx to monitoring
  template:
    src: nginx.j2
    dest: /etc/monit/conf.d/nginx
    mode: 0600
    owner: root
    group: root
  notify:
    - reload monit
