---
# file: roles/hostname/tasks/main.yml

- name: make sure the hostname is updated (1) - hostname cmd
  command: hostname {{ hostname }}
  changed_when: no

- name: make sure the hostname is updated (2) - (/etc/hostname)
  template:
    src: etc_hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: make sure the hostname is updated (3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1 {{ hostname }} {{ hostname }}"
    line: "127.0.0.1 {{ hostname }} {{ hostname }}"
    state: present
