---
# file: roles/common/tasks/main.yml
- name: install basic tools
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - build-essential
    - tree
    - vim
    - gawk 
    - libreadline6-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3 
    - autoconf
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - libtool
    - bison
    - pkg-config
    - libffi-dev
    - git
    - htop
    - python-passlib
    - nodejs
    - libgmp3-dev
    - ncdu
