---
# file: roles/application/tasks/directories.yml
- name: create application directories
  become: yes
  become_method: sudo
  become_user: "{{ deployer_user }}"
  file:
    path: /home/{{ deployer_user }}/application/shared/{{ item }}
    owner: "{{ deployer_user }}"
    state: directory
  with_items:
    - log
    - config
    - tmp
    - tmp/sockets
    - tmp/pids
  tags:
    - app

- name: upload shared files
  become: yes
  become_method: sudo
  become_user: "{{ deployer_user }}"
  template:
    src: "{{ item }}.j2"
    dest: /home/{{ deployer_user }}/application/shared/config/{{ item }}
    owner: "{{ deployer_user }}"
    group: "{{ deployer_user }}"
    mode: 0644
  with_items:
    - database.yml
    - secrets.yml
    - unicorn.rb
  tags:
    - app
