---
# file: roles/application/tasks/monitoring.yml

- name: make sure we have passwdfile for monit
  become: yes
  become_method: sudo
  htpasswd:
    path: /etc/nginx/monit_passwd
    name: "{{ monit_user }}"
    password: "{{ monit_password }}"
    owner: root
    group: www-data
    mode: 0644
  tags:
    - monitoring
    - monit

- name: make sure we have passwdfile for munin
  become: yes
  become_method: sudo
  htpasswd:
    path: /etc/nginx/munin_passwd
    name: "{{ munin_user }}"
    password: "{{ munin_password }}"
    owner: root
    group: www-data
    mode: 0644
  tags:
    - monitoring
    - munin
