---
# file: roles/application/tasks/nginx.yml
- name: be sure site is configured
  become: yes
  become_method: sudo
  template:
    src: site.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
    owner: root
    group: root
    mode: 0644

- name: enable site
  become: yes
  become_method: sudo
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link
  notify:
    - reload nginx
