---
# file: roles/munin/tasks/configure.yml

- name: make sure munin is configured
  template:
    src: munin.conf.j2
    dest: /etc/munin/munin.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - monitoring
    - munin
